name: "miniDSP 2x4HD Green"
slug: "minidsp_green"
description: "Работает на HA Green 2025.11+"
version: "1.4"
arch:
  - aarch64
startup: application
boot: auto
ports:
  8080/tcp: 8080
options: {}
schema: {}
