name: "miniDSP 2x4HD Green Fixed"
slug: "minidsp_green_fixed"
description: "Управление miniDSP 2x4 HD на HA Green"
version: "1.3"
arch:
  - aarch64
startup: application
boot: auto
map:
  - "8080:8080"
host_network: false
options: {}
schema: {}
