name: "miniDSP 2x4HD"
slug: "minidsp_fixed"
description: "Рабочий контроллер miniDSP 2x4 HD"
version: "1.0.3"
arch:
  - aarch64
  - armv7
  - amd64
  - i386
startup: application
boot: auto
ports:
  8080/tcp: 8080
host_network: false
devices:
  - /dev/bus/usb:/dev/bus/usb   # если будешь HID использовать потом
options: {}
schema: {}
